from binary_search import *
import unittest

class testBinSearch(unittest.TestCase):
    def testSearch(self):
        self.a = [ii for ii in range(30)]
        self.bs = BinarySearch(self.a)
        self.bs.Step(14)
        self.assertEqual(self.bs.GetResult(),1,'test1')
        self.bs = BinarySearch(self.a)
        self.bs.Step(15)
        self.assertEqual(self.bs.GetResult(), 0, 'test2')
        self.bs = BinarySearch(self.a)
        while self.bs.GetResult() == 0:
            self.bs.Step(31)
        self.assertEqual(self.bs.GetResult(), -1, 'test3')
        self.bs = BinarySearch(self.a)
        while self.bs.GetResult() != 1:
            self.assertEqual(self.bs.GetResult(), 0, 'test4')
            self.bs.Step(2)
        self.assertEqual(self.bs.GetResult(), 1, 'test5')
        self.bs = BinarySearch([1])
        self.bs.Step(2)
        self.assertEqual(self.bs.GetResult(), -1, 'test6')
        self.bs = BinarySearch([1])
        self.bs.Step(1)
        self.assertEqual(self.bs.GetResult(), 1, 'test7')
        self.bs = BinarySearch([])
        self.bs.Step(1)
        self.assertEqual(self.bs.GetResult(), -1, 'test8')
        # test for 1..99 array, search for 49 (48 idx)
        self.a = [ii for ii in range(1, 100)]
        self.bs = BinarySearch(self.a)
        self.assertEqual(self.bs.GetResult(), 0, 'test9')
        self.assertEqual(self.bs.Left, 0, 'test9')
        self.assertEqual(self.bs.Right, 98, 'test9')
        self.bs.Step(49)
        self.assertEqual(self.bs.GetResult(), 0, 'test9')
        self.assertEqual(self.bs.Left, 0, 'test9')
        self.assertEqual(self.bs.Right, 48, 'test9')
        self.bs.Step(49)
        self.assertEqual(self.bs.GetResult(), 0, 'test9')
        self.assertEqual(self.bs.Left, 25, 'test9')
        self.assertEqual(self.bs.Right, 48, 'test9')
        self.bs.Step(49)
        self.assertEqual(self.bs.GetResult(), 0, 'test9')
        self.assertEqual(self.bs.Left, 37, 'test9')
        self.assertEqual(self.bs.Right, 48, 'test9')
        self.bs.Step(49)
        self.assertEqual(self.bs.GetResult(), 0, 'test9')
        self.assertEqual(self.bs.Left, 43, 'test9')
        self.assertEqual(self.bs.Right, 48, 'test9')
        self.bs.Step(49)
        self.assertEqual(self.bs.GetResult(), 0, 'test9')
        self.assertEqual(self.bs.Left, 46, 'test9')
        self.assertEqual(self.bs.Right, 48, 'test9')
        self.bs.Step(100)
        self.assertEqual(self.bs.GetResult(), -1, 'test9')
        self.assertEqual(self.bs.Left, 48, 'test9')
        self.assertEqual(self.bs.Right, 48, 'test9')
        self.a = [1, 3, 4]
        self.bs = BinarySearch(self.a)
        self.bs.Step(2)
        self.assertEqual(self.bs.GetResult(), -1, 'test10')


unittest.main(verbosity=2)